baseURL = "https://danilf16.github.io/"
title = "Danil Prokhorenko"
theme = "ananke"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[languages]

  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content/en"

  [languages.ru]
    languageName = "Русский"
    weight = 2
    contentDir = "content/ru"